# install rethinkdb by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure rethinkdb
- name: Create rethinkdb data directory
  file:
    path: /data/rethindb
    state: directory
    recurse: yes
    owner: rethinkdb
    group: rethinkdb

- name: Create rethinkdb logs file
  file:
    path: /data/logs/rethinkdb
    state: file
    owner: rethinkdb
    group: rethinkdb
    mode: '0755'
    
- name: Add rethinkdb data
  shell: | 
    rethinkdb create -d /data/rethindb
    chown -R rethinkdb.rethinkdb /data/rethindb
  failed_when: false

- name: Copy rethinkdb configure file
  shell: cp /etc/rethinkdb/default.conf.sample  /etc/rethinkdb/instances.d/instance.conf

- name: Copy rethinkdb service file
  copy:
    src: rethinkdb.service
    dest: /lib/systemd/system/rethinkdb.service
    
- name: Configure rethinkdb logs file
  lineinfile:
    path: /etc/rethinkdb/instances.d/instance.conf
    regexp: '^# log-file=/var/log/rethinkdb'
    line: 'log-file=/data/logs/rethinkdb'
    state: present
    backrefs: yes
    
- name: Configure rethinkdb data dir
  lineinfile:
    path: /etc/rethinkdb/instances.d/instance.conf
    regexp: '^# directory=/var/lib/rethinkdb/default'
    line: 'directory=/data/rethindb'
    state: present
    backrefs: yes

- name: Insert nginx login validate 
  blockinfile:
    path: /etc/nginx/conf.d/default.conf
    block: |
      auth_basic "Restricted";                                
      auth_basic_user_file /etc/nginx/.htpasswd;

- name: Create password file with htpasswd
  shell: htpasswd -bc /etc/nginx/.htpasswd admin admin

- name: Restart rethinkdb
  service:
    name: '{{item}}'
    state: restarted
    enabled: yes
  with_items:
    - rethinkdb
    - nginx
    
- name: Create link 
  shell: |
    mkdir -p /data/logs/rethinkdb
    ln -sf /data/rethinkdb/log_file /data/logs/rethinkdb/log_file
  
# Check version,
- block:
  - name: Check Rethinkdb Version
    shell: sudo echo $(rethinkdb --version) |sudo  tee -a /data/logs/install_version.txt

# check service state
- name: Check Rethinkdb Service
  shell: systemctl status rethinkdb | grep Active*
  register: check_rethinkdb_service
  notify: check_rethinkdb_service
